# https://travis-ci.org/danielkoster/argosd
language: python
python:
  - 3.4
  - 3.5
install:
  - pip install -r requirements-test.txt --quiet
script:
  - nosetests tests -v --with-coverage --cover-package=argosd --cover-inclusive --cover-xml
  - pep8 argosd
  - pep8 tests
after_success:
  - python-codacy-coverage -r coverage.xml
